# Generated by Django 4.1.7 on 2023-02-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
